### PR TITLE
add Docker support

### PR DESCRIPTION
**Pull request by yeya24**
- add Docker support
- add go mod
- update Readme

### CODE REVIEW

**Comment by WangYihang** [comment]
Hey, yeya24, thank you for your excellent work!
I will check it out tonight! 😄

**Comment by yeya24** [comment]
You are welcome! @WangYihang It is really a nice project.
You can merge this after u test it. :smile:

**Comment by WangYihang** [comment]
merged.

yeya24 <notifications@github.com> 于2019年7月2日周二 下午7:27写道：

**Comment by WangYihang** [comment]
Merged.

**Pull request merged**
